name: nu_bank_clone
description: A nu bank apps clone.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter   

  intl: ^0.17.0      

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  google_fonts: ^3.0.1
  brasil_fields: ^1.4.5
  http: ^0.13.5
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7 

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
